enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 80
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
cinderscapes = true
azurelib = true
mcwroofs = true
mcwfences = true
bountiful = true
mutantmonsters = true
mythicmobs = true
barteringstation = true
alloy_forgery = true
croptopia = true
oxidized = true
mythicmounts = true
chimes = true
betterend = true
twigs = true
spellbladenext = true
friendsandfoes = true
runes = true
natures_spirit = true
amethyst_update = true
legacies_and_legends = true
mythicupgrades = true
aquamirae = true
things = true
mcwbridges = true
mcwtrpdoors = true
mcda = true
conjuring = true
handcrafted = true
ftbquests = true
lolmcv = true
bewitchment = true
pumpeddesertfabric = true
graveyard = true
netherchested = true
disenchanter = true
spell_engine = true
customportalapi = true
hybrid-aquatic = true
mcwdoors = true
ironchests = true
minecells = true
supplementaries = true
magnumtorch = true
deeperdarker = true
beachparty = true
clutter = true
soulsweapons = true
golemfirststonemod = true
minecraft = true
fwaystones = true
swampier_swamps = true
regions_unexplored = true
snifferplus = true
betterarcheology = true
travelersbackpack = true
creeperoverhaul = true
endermanoverhaul = true
adventurez = true
bosses_of_mass_destruction = true
decorative_blocks = true
besmirchment = true
universal_graves = true
vinery = true
illagerinvasion = true
netherdepthsupgrade = true
